#AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"DataChunk": "00_core.ipynb",
         "ContiguousRecord": "00_core.ipynb",
         "RecordMaster": "00_core.ipynb",
         "Data_Pipe": "00_core.ipynb",
         "export_record": "00_core.ipynb",
         "import_record": "00_core.ipynb",
         "extend_sync_timepoints": "01_utils.ipynb",
         "align_sync_timepoints": "01_utils.ipynb",
         "resample_to_timepoints": "01_utils.ipynb",
         "stim_to_dataChunk": "01_utils.ipynb",
         "spike_to_dataChunk": "01_utils.ipynb",
         "parse_stim_args": "01_utils.ipynb",
         "eyetrack_stim_inten": "02_processing.ipynb",
         "process_sta_batch": "02_processing.ipynb",
         "cross_correlation": "02_processing.ipynb",
         "sigmoid": "03_modelling.ipynb",
         "gaussian": "03_modelling.ipynb",
         "gaussian_2D": "03_modelling.ipynb",
         "sum_of_gaussian": "03_modelling.ipynb",
         "sum_of_2D_gaussian": "03_modelling.ipynb",
         "fit_nonlinearity": "03_modelling.ipynb",
         "fit_spatial_sta": "03_modelling.ipynb"}

modules = ["core.py",
           "utils.py",
           "processing.py",
           "modelling.py"]

git_url = "https://github.com/Tom-TBT/theonerig/tree/master/"

def custom_doc_links(name): return None