#AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"DataChunk": "00_core.ipynb",
         "ContiguousRecord": "00_core.ipynb",
         "RecordMaster": "00_core.ipynb",
         "extend_sync_timepoints": "01_utils.ipynb",
         "align_sync_timepoints": "01_utils.ipynb",
         "resample_to_timepoints": "01_utils.ipynb",
         "stim_to_dataChunk": "01_utils.ipynb",
         "spike_to_dataChunk": "01_utils.ipynb",
         "parse_stim_args": "01_utils.ipynb"}

modules = ["core.py",
           "utils.py"]

git_url = "https://github.com/Tom-TBT/theonerig/tree/master/"

def custom_doc_links(name): return None