# AUTOGENERATED! DO NOT EDIT! File to edit: 12_synchro.processing.ipynb (unless otherwise specified).

__all__ = ['get_thresholds']

# Cell
import numpy as np

# Cell
def get_thresholds(data):
    max_val = max(data[int(len(data)/2):int(len(data)*3/4)]) #Looking for a max in a quarter of the data, from the middle
    high_thresh = max_val*3/4 # High threshold set at 3/4th of the max
    low_thresh  = max_val*1/4
    return low_thresh, high_thresh